### ISSUE TITLE
Tutorial unable to end properly

### ISSUE THREAD

**Issue by APratham** [GoogleCloudPlatform/cloud-shell-tutorials#16]
I have followed all the instructions and made a Cloud Shell tutorial. But I am not able to get the confetti image that is there at the end of the official tutorial when viewing it in Google Cloud console. What is the reason for this? Do I need to add some additional code for the confetti to appear at the end? Any help in this regard will be greatly appreciated.

I also wanted to know how I can add line breaks. < br > doesn't seem to work as the tutorials are not using Markdown/HTML

**Comment by jscud** [comment]
For the icon at the end, try using <walkthrough-conclusion-trophy>

The tutorial renderer doesn't support most HTML elements. Are you wanting to add multiple blank lines?

**Comment by APratham** [comment]
Thank you so much @jscud. Yes I wanted to add a few blank lines to make the text look better. Is that possible?

**Comment by APratham** [comment]
Sorry for the trouble. Reiterating my query from earlier, @jscud is it possible to add a few blank lines to the tutorials we create?

**Comment by APratham** [comment]
Closing the issue due to inactivity
